CREATE SEQUENCE IF NOT EXISTS SEQ_BLOCK
    START WITH 1
    INCREMENT BY 1;

CREATE TABLE IF NOT EXISTS BLOCK (
    ID BIGINT PRIMARY KEY DEFAULT nextval('SEQ_BLOCK'),
    NAME VARCHAR2(255),
    REGISTRY_NAME VARCHAR2(255),
    TYPE VARCHAR2(255),
    MODALITY VARCHAR2(255),
    CREATE_DATE TIMESTAMP,
    CREATE_BY VARCHAR2(255),
    UPDATE_DATE TIMESTAMP,
    UPDATE_BY VARCHAR2(255),
    DELETE_DATE TIMESTAMP,
    DELETE_BY VARCHAR2(255)
);

CREATE TABLE IF NOT EXISTS BLOCK_VERSION (
    ID BIGINT PRIMARY KEY DEFAULT,
    BLOCK_ID BIGINT REFERENCES BLOCK(ID),
    VERSION INT NOT NULL,
    CODE TEXT NOT NULL,
    PARAMS JSONB,
    INPUTS JSONB,
    OUTPUTS JSONB,
    VALIDATED_AT TIMESTAMP,

    CREATE_DATE   TIMESTAMP,
    CREATE_BY     VARCHAR(255),
    UNIQUE (BLOCK_ID, VERSION)
);